name: terraform deployment

on:
    push:
        branches:
        - "*"

jobs:
    terraform_deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set Up Terraform
          uses: hashicorp/setup-terraform@v1
  
        - name: Configure Environment
          run: |
            echo "TF_CLI_ARGS_init=-backend-config=password=${{ secrets.GITHUB_TOKEN }}" >> $GIHUB_ENV

        - name: Terraform Init
          run: terraform init
  
        - name: Terraform Apply
          run: terraform apply -auto-approve
  