name: terraform deployment

on:
    push:
        branches:
        - "*"

jobs:
    terraform_deploy:
      runs-on: ubuntu-latest

      env: 
        TF_HTTP_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set Up Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          run: terraform init
  
        - name: Terraform Apply
          run: terraform apply -auto-approve
  