name: terraform deployment

on:
    push:
        branches:
        - "*"

jobs:
    terraform_deploy:
      runs-on: ubuntu-latest

      env: 
        TF_HTTP_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            sso-start-url: https://hdm-mi7.awsapps.com/start#
            sso-region: eu-north-1
            sso-account-id: 856591169022
            sso-role-name: ChatScapeAdministrator
            aws-region: eu-north-1

        - name: Set Up Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          run: terraform init
  
        - name: Terraform Apply
          run: terraform apply -auto-approve
  